id = "stimulus"
name = "Stimulus LSP"
description = "Stimulus LSP support."
version = "0.1.3"
schema_version = 1
authors = ["Vitaly Slobodin <vitaliy.slobodin@gmail.com>"]
repository = "https://github.com/vitallium/zed-stimulus"

[language_servers.stimulus]
name = "Stimulus"
languages = ["HTML", "HTML/ERB", "PHP"]
