---
name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: vitallium/setup-wasi-sdk-action@974e0ef073d1c60c6d6bd6ba13a91884598be2f9
      - run: rustc -V
      - run: cargo build --release --target wasm32-wasip1
