---
name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup WASI
        uses: vitallium/setup-wasi-sdk-action@49fee04582916b6dfb71c7f70be6493786399f02
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasip1
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target wasm32-wasip1 --release
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target wasm32-wasip1
